import {useEffect,useRef} from "react";
import {bySpecies,npcs} from "../data";
import {drawNpcSprite,drawSpeciesSprite} from "../sprites";
import type {NpcStage,Pet,PlantState} from "../types";

interface Props{pet:Pet;action:string;theme:string;equippedDecor?:string[];plantState?:PlantState;companion?:{npcId:string;stage:NpcStage};}
export function PetCanvas({pet,action,theme,equippedDecor=[],plantState,companion}:Props){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const c=canvas.getContext("2d");if(!c)return;let frame=0,raf=0,last=0;const s=bySpecies(pet.speciesId),wallpaper=equippedDecor.includes("wallpaper"),nightlight=equippedDecor.includes("nightlight");const draw=(t:number)=>{if(t-last>230){frame++;last=t}const night=new Date().getHours()<7||new Date().getHours()>19;c.imageSmoothingEnabled=false;drawRoom(c,night,wallpaper,nightlight,pet.isSleeping,plantState,frame);let petX=80,bob=(frame%2)*2+(action==="happy"?Math.sin(t/70)*4:0);if(action.startsWith("feed-pet-approach")||action.startsWith("feed-bite")||action.startsWith("feed-chew"))petX=91;drawSpeciesSprite(c,s,{x:petX,y:79+bob},1,action.includes("reaction")?"happy":pet.isSleeping?"sleep":pet.isSick?"sick":action,{pet,frame,senior:pet.lifeStage==="senior",legacyCosmetic:pet.legacyCosmetic});drawAction(c,action,frame,pet.poopCount);if(!action.startsWith("clean-poop"))for(let i=0;i<pet.poopCount;i++)drawPoop(c,12+i*14,96);if(pet.isSleeping){c.fillStyle="#69558a";c.font="bold 10px monospace";c.fillText("Z",108,53);c.fillText("z",119,44)}if(companion){const npc=npcs.find(n=>n.id===companion.npcId);if(npc)drawNpcSprite(c,npc.looks[companion.stage],{x:125,y:88},.72,"happy",frame)}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf)},[pet,action,theme,equippedDecor,plantState,companion]);return <canvas ref={ref} width="160" height="144" className="pet-canvas" data-sprite-id={pet.speciesId} role="img" aria-label={`${bySpecies(pet.speciesId).name}正在${actionLabel(action)}`}/>}
function drawRoom(c:CanvasRenderingContext2D,night:boolean,wallpaper:boolean,nightlight:boolean,sleeping:boolean,plant:PlantState|undefined,frame:number){c.fillStyle=night?"#394766":wallpaper?"#dff0d7":"#d9f2df";c.fillRect(0,0,160,144);c.fillStyle=night?"#68769b":wallpaper?"#f2dbe9":"#fff6cf";c.fillRect(10,12,42,38);c.fillStyle=night?"#f8e58a":"#8fd4e4";c.fillRect(15,17,32,28);if(wallpaper){c.fillStyle="#efbad0";c.fillRect(8,52,144,3);for(let x=8;x<152;x+=24){c.fillRect(x,26,3,3);c.fillRect(x+8,38,3,3)}}c.fillStyle=wallpaper?"#e9d4b8":"#fff8e8";c.fillRect(0,102,160,42);c.fillStyle=wallpaper?"#ba8f78":"#deb9cc";for(let x=0;x<160;x+=16)c.fillRect(x,116+(x%32?4:0),16,3);c.fillStyle="#7a5576";c.fillRect(112,62,37,40);c.fillStyle=wallpaper?"#cce5bd":"#f0c9dd";c.fillRect(116,67,29,31);if(nightlight&&(night||sleeping)){c.fillStyle="#fff1a8";c.fillRect(137,70,6,17);c.fillRect(132,68,11,6);c.fillStyle=`rgba(255,240,150,${frame%2?.13:.1})`;c.fillRect(126,59,30,38)}if(plant?.placed){c.fillStyle="#9b6b59";c.fillRect(101,91,11,10);c.fillStyle="#6ca46d";c.fillRect(104,86,4,7);if(plant.growth>0){c.fillRect(99,83,6,5);c.fillRect(108,80,5,7)}if(plant.growth>1){c.fillStyle="#e888ad";c.fillRect(101,77,5,5);c.fillStyle="#f6d770";c.fillRect(103,78,2,2)}}}
function drawPoop(c:CanvasRenderingContext2D,x:number,y:number){c.fillStyle="#9b7a6c";c.fillRect(x,y,8,7);c.fillStyle="#fff3c4";c.fillRect(x+2,y-2,4,2)}
function drawAction(c:CanvasRenderingContext2D,a:string,frame:number,poops:number){if(a.startsWith("feed")){const phase=a.split("-").slice(1).join("-");let size=phase==="bite"?5:phase==="chew"?3:7,x=phase==="food-enter"?130-frame*8:103;c.fillStyle="#ef799d";c.fillRect(x,83,size,size);if(["bite","chew","reaction"].includes(phase))for(let i=0;i<5;i++){c.fillStyle=i%2?"#ffe5a2":"#ef799d";c.fillRect(96+(i*7+frame*3)%30,78+(i*5)%18,2,2)}if(phase==="reaction"){c.fillStyle="#e85488";c.fillRect(99,55,5,5);c.fillRect(106,49,4,4)}}if(a.startsWith("clean-poop")){const remaining=Math.max(0,poops-Math.floor(frame/2));for(let i=0;i<remaining;i++)drawPoop(c,12+i*14,96);c.fillStyle="#7b9aa0";c.fillRect(8+frame*5,84,10,12);c.fillStyle="#fff7b2";for(let i=remaining;i<poops;i++)c.fillRect(15+i*14,91,3,3)}if(a.startsWith("clean-sweep")){const x=(frame*17)%135;c.fillStyle="#9c704d";c.fillRect(x,72,4,28);c.fillStyle="#dfb06f";c.fillRect(x-6,96,17,6);for(let i=0;i<5;i++){c.fillStyle="#b78b78";c.fillRect(Math.min(150,x+i*5),101,2,2)}}if(a.startsWith("clean-bath")){c.fillStyle="#a5dbe8";c.fillRect(52,81,56,25);c.fillStyle="#fff";for(let i=0;i<10;i++)c.fillRect(48+(i*13+frame*4)%65,92-(i*9+frame*4)%36,3+(i%2),3+(i%2));c.fillStyle="#79b8cd";c.fillRect(49,102,62,5)}if(a==="evolve"){c.fillStyle="#fff6a4";for(let i=0;i<12;i++)c.fillRect((i*19+frame*4)%150,20+(i*13)%85,3,3)}}
function actionLabel(a:string){return a.startsWith("feed")?"享用食物":a.startsWith("clean")?"進行清潔":({idle:"休息",happy:"開心地跳躍",sick:"生病",gift:"收禮物",wedding:"參加婚禮",evolve:"進化"} as Record<string,string>)[a]??"活動"}
