import Dexie,{type EntityTable} from "dexie";
import {migrateSaveV1,isSaveV2} from "./migrations";
import type {GameState,InventoryItem,Pet,Relationship,SaveFile} from "./types";
export interface Log{id?:number;at:number;type:string;message:string}
export interface RecordRow{id:string;value:unknown}
export interface Snapshot{id?:number;at:number;data:unknown}
const stores={pets:"id,lastUpdatedAt",gameState:"id,lastSavedAt",inventory:"id,itemId",activityLogs:"++id,at,type",npcRelationships:"npcId,affection",achievements:"id",evolutionAlbum:"id",settings:"id",saveSnapshots:"++id,at"};
export const db=new Dexie("PicoPalsDB") as Dexie&{pets:EntityTable<Pet,"id">;gameState:EntityTable<GameState,"id">;inventory:EntityTable<InventoryItem,"id">;activityLogs:EntityTable<Log,"id">;npcRelationships:EntityTable<Relationship,"npcId">;achievements:EntityTable<RecordRow,"id">;evolutionAlbum:EntityTable<RecordRow,"id">;settings:EntityTable<RecordRow,"id">;saveSnapshots:EntityTable<Snapshot,"id">};
db.version(1).stores(stores);
db.version(2).stores(stores).upgrade(async tx=>{const pet=await tx.table("pets").toCollection().first(),game=await tx.table("gameState").get("main");if(!pet||!game)return;const settingsRows=await tx.table("settings").toArray();const legacy={schemaVersion:1,exportedAt:Date.now(),pet,game,inventory:await tx.table("inventory").toArray(),relationships:await tx.table("npcRelationships").toArray(),album:(await tx.table("evolutionAlbum").toArray()).map((x:{id:string})=>x.id),achievements:(await tx.table("achievements").toArray()).map((x:{id:string})=>x.id),settings:Object.fromEntries(settingsRows.map((x:{id:string;value:unknown})=>[x.id,x.value]))};await tx.table("saveSnapshots").add({at:Date.now(),data:legacy});const migrated=migrateSaveV1(legacy);await tx.table("pets").put(migrated.pet);await tx.table("npcRelationships").clear();await tx.table("npcRelationships").bulkPut(migrated.relationships);await tx.table("settings").clear();await tx.table("settings").bulkPut([...Object.entries(migrated.settings).map(([id,value])=>({id,value})),{id:"__saveMeta",value:metaOf(migrated)}])});
const metaOf=(s:SaveFile)=>({schemaVersion:2,albumEntries:s.albumEntries,npcProgress:s.npcProgress,unlockedDecor:s.unlockedDecor,equippedDecor:s.equippedDecor,plantState:s.plantState,legacyTraits:s.legacyTraits,evolutionHistory:s.evolutionHistory,itemDefinitionsVersion:s.itemDefinitionsVersion});
export async function loadSave():Promise<SaveFile|null>{const pet=await db.pets.toCollection().first(),game=await db.gameState.get("main");if(!pet||!game)return null;const inventory=await db.inventory.toArray(),relationships=await db.npcRelationships.toArray(),album=(await db.evolutionAlbum.toArray()).map(x=>x.id),achievements=(await db.achievements.toArray()).map(x=>x.id),rows=await db.settings.toArray(),settings=Object.fromEntries(rows.filter(x=>x.id!=="__saveMeta").map(x=>[x.id,x.value])),meta=rows.find(x=>x.id==="__saveMeta")?.value as Partial<SaveFile>|undefined;const raw={schemaVersion:meta?.schemaVersion??1,exportedAt:Date.now(),pet,game,inventory,relationships,album,achievements,settings,...meta};return isSaveV2(raw)?raw:migrateSaveV1(raw)}
export async function persistSave(save:SaveFile){await db.transaction("rw",[db.pets,db.gameState,db.inventory,db.npcRelationships,db.evolutionAlbum,db.achievements,db.settings],async()=>{await db.pets.clear();await db.pets.add(save.pet);await db.gameState.put({...save.game,lastSavedAt:Date.now()});await db.inventory.clear();await db.inventory.bulkPut(save.inventory);await db.npcRelationships.clear();await db.npcRelationships.bulkPut(save.relationships);await db.evolutionAlbum.clear();await db.evolutionAlbum.bulkPut(save.album.map(id=>({id,value:true})));await db.achievements.clear();await db.achievements.bulkPut(save.achievements.map(id=>({id,value:true})));await db.settings.clear();await db.settings.bulkPut([...Object.entries(save.settings).map(([id,value])=>({id,value})),{id:"__saveMeta",value:metaOf(save)}])})}
export function validateSave(data:unknown){if(!data||typeof data!=="object")return false;const x=data as {schemaVersion?:number;pet?:unknown;game?:unknown;inventory?:unknown;relationships?:unknown};return(x.schemaVersion===1||x.schemaVersion===2)&&!!x.pet&&!!x.game&&Array.isArray(x.inventory)&&Array.isArray(x.relationships)}
export async function importSave(data:unknown){if(!validateSave(data))throw new Error("存檔版本不相容");const current=await loadSave();if(current)await db.saveSnapshots.add({at:Date.now(),data:current});const next=isSaveV2(data)?data:migrateSaveV1(data);await persistSave(next);return next}
export async function restoreSnapshot(){const snap=await db.saveSnapshots.orderBy("at").last();if(!snap)throw new Error("沒有可恢復的快照");if(!validateSave(snap.data))throw new Error("快照格式無效");const data=isSaveV2(snap.data)?snap.data:migrateSaveV1(snap.data);await persistSave(data);return data}
export async function resetDatabase(){await db.delete();await db.open()}
