import Dexie,{type EntityTable} from "dexie";
import type {GameState,InventoryItem,Pet,Relationship,SaveFile} from "./types";
export interface Log{id?:number;at:number;type:string;message:string}
export interface RecordRow{id:string;value:unknown}
export interface Snapshot{id?:number;at:number;data:SaveFile}
export const db=new Dexie("PicoPalsDB") as Dexie&{pets:EntityTable<Pet,"id">;gameState:EntityTable<GameState,"id">;inventory:EntityTable<InventoryItem,"id">;activityLogs:EntityTable<Log,"id">;npcRelationships:EntityTable<Relationship,"npcId">;achievements:EntityTable<RecordRow,"id">;evolutionAlbum:EntityTable<RecordRow,"id">;settings:EntityTable<RecordRow,"id">;saveSnapshots:EntityTable<Snapshot,"id">};
db.version(1).stores({pets:"id,lastUpdatedAt",gameState:"id,lastSavedAt",inventory:"id,itemId",activityLogs:"++id,at,type",npcRelationships:"npcId,affection",achievements:"id",evolutionAlbum:"id",settings:"id",saveSnapshots:"++id,at"});
export async function loadSave():Promise<SaveFile|null>{const pet=await db.pets.toCollection().first(),game=await db.gameState.get("main");if(!pet||!game)return null;return{schemaVersion:1,exportedAt:Date.now(),pet,game,inventory:await db.inventory.toArray(),relationships:await db.npcRelationships.toArray(),album:(await db.evolutionAlbum.toArray()).map(x=>x.id),achievements:(await db.achievements.toArray()).map(x=>x.id),settings:Object.fromEntries((await db.settings.toArray()).map(x=>[x.id,x.value]))}}
export async function persistSave(save:SaveFile){await db.transaction("rw",[db.pets,db.gameState,db.inventory,db.npcRelationships,db.evolutionAlbum,db.achievements,db.settings],async()=>{await db.pets.clear();await db.pets.add(save.pet);await db.gameState.put({...save.game,lastSavedAt:Date.now()});await db.inventory.clear();await db.inventory.bulkPut(save.inventory);await db.npcRelationships.clear();await db.npcRelationships.bulkPut(save.relationships);await db.evolutionAlbum.clear();await db.evolutionAlbum.bulkPut(save.album.map(id=>({id,value:true})));await db.achievements.clear();await db.achievements.bulkPut(save.achievements.map(id=>({id,value:true})));await db.settings.clear();await db.settings.bulkPut(Object.entries(save.settings).map(([id,value])=>({id,value})))})}
export function validateSave(data:unknown):data is SaveFile{if(!data||typeof data!=="object")return false;const x=data as Partial<SaveFile>;return x.schemaVersion===1&&!!x.pet&&!!x.game&&Array.isArray(x.inventory)&&Array.isArray(x.relationships)}
export async function importSave(data:unknown){if(!validateSave(data))throw new Error("存檔版本不相容");const current=await loadSave();if(current)await db.saveSnapshots.add({at:Date.now(),data:current});await persistSave(data);return data}
export async function restoreSnapshot(){const snap=await db.saveSnapshots.orderBy("at").last();if(!snap)throw new Error("沒有可恢復的快照");await persistSave(snap.data);return snap.data}
export async function resetDatabase(){await db.delete();await db.open()}
