import {bySpecies,stageMinutes} from "./data";
import type {Food,GameState,Gift,Npc,OfflineSummary,Pet,Relationship,SaveFile,Species,Stage} from "./types";
export const TIME_SCALE=1;
export const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
export function createPet(now=Date.now()):Pet{return{id:crypto.randomUUID?.()??`pet-${now}`,name:"波波",speciesId:"stardust-egg",stage:"egg",personality:"平靜",birthAt:now,lastUpdatedAt:now,ageMinutes:0,health:90,fullness:75,happiness:80,cleanliness:90,energy:85,affection:50,weight:2.5,idealWeightMin:2,idealWeightMax:3,poopCount:0,isSick:false,isSleeping:false,isAlive:true,careMistakes:0,mealsToday:0,snacksToday:0,gamesPlayedToday:0,giftsReceived:0,behaviorTags:{active:0,sweetTooth:0,healthy:1,clean:1,affectionate:1,calm:1,neglected:0}}}
export function createGame(now=Date.now()):GameState{return{id:"main",coins:80,lastSavedAt:now,highScores:{catch:0,memory:0,ribbon:0},weightHistory:[{at:now,value:2.5}],generation:1,clockAnomalies:0,history:[]}}
export function feedPet(pet:Pet,food:Food):Pet{if(pet.fullness>=95)return pet;const snack=food.kind==="snack";const excess=snack&&pet.snacksToday>=3;return{...pet,fullness:clamp(pet.fullness+food.fullness),happiness:clamp(pet.happiness+food.happiness),health:clamp(pet.health+food.health-(excess?2:0)),weight:+(pet.weight+food.weight).toFixed(1),mealsToday:pet.mealsToday+(snack?0:1),snacksToday:pet.snacksToday+(snack?1:0),behaviorTags:{...pet.behaviorTags,sweetTooth:pet.behaviorTags.sweetTooth+(excess?2:snack?1:0),healthy:pet.behaviorTags.healthy+(food.health>1?1:0)}}}
export function applyGameResult(pet:Pet,score:number):Pet{return{...pet,happiness:clamp(pet.happiness+clamp(8+Math.floor(score/5),8,20)),fullness:clamp(pet.fullness-6),energy:clamp(pet.energy-8),weight:+Math.max(.5,pet.weight-.2).toFixed(1),gamesPlayedToday:pet.gamesPlayedToday+1,behaviorTags:{...pet.behaviorTags,active:pet.behaviorTags.active+2}}}
export function cleanPet(pet:Pet,kind:"poop"|"sweep"|"bath"):Pet{return{...pet,poopCount:kind==="poop"?0:pet.poopCount,cleanliness:clamp(pet.cleanliness+(kind==="bath"?35:kind==="poop"?25:18)),happiness:clamp(pet.happiness+3),behaviorTags:{...pet.behaviorTags,clean:pet.behaviorTags.clean+1}}}
export function restPet(pet:Pet):Pet{return{...pet,isSleeping:!pet.isSleeping,energy:clamp(pet.energy+(!pet.isSleeping?15:0)),health:clamp(pet.health+(!pet.isSleeping?2:0)),behaviorTags:{...pet.behaviorTags,calm:pet.behaviorTags.calm+1}}}
export function treatPet(pet:Pet):Pet{return{...pet,isSick:false,sicknessType:undefined,health:clamp(pet.health+12),energy:clamp(pet.energy+8),happiness:clamp(pet.happiness+4)}}
const stageOrder:Stage[]=["egg","baby","child","teen","adult"];
export function careScore(p:Pet){return p.health*.3+p.happiness*.2+p.cleanliness*.2+p.fullness*.1+clamp(p.gamesPlayedToday*10)*.1+p.affection*.1-p.careMistakes*4;}
export function chooseEvolution(p:Pet):Species{const score=careScore(p),tags=p.behaviorTags;const choices=({egg:["pomu"],baby:tags.clean>tags.active?["cloudkit","bloompup"]:["berrybun","starlamb"],child:p.speciesId==="berrybun"?[score>72?"ribbonbun":"sugarfox"]:p.speciesId==="cloudkit"?[score>70?"pearlseal":"moonmew"]:[score>72?"bloomdeer":"starpup"],teen:p.speciesId==="ribbonbun"?[score>75?"rosette":"honeybell"]:p.speciesId==="sugarfox"?[score>70?"aurora":"honeybell"]:p.speciesId==="moonmew"?[score>72?"celestia":"velvet"]:p.speciesId==="pearlseal"?[score>72?"opaline":"mallow"]:p.speciesId==="bloomdeer"?[score>70?"florielle":"mallow"]:[score>70?"honeybell":"velvet"],adult:[p.speciesId]} as Record<Stage,string[]>)[p.stage];return bySpecies(choices[0]!)}
export function evolveIfReady(p:Pet):Pet{if(p.stage==="adult")return p;const needed=stageMinutes[p.stage];if(p.ageMinutes<needed)return p;const s=chooseEvolution(p),nextStage=stageOrder[stageOrder.indexOf(p.stage)+1]??"adult";return{...p,speciesId:s.id,stage:nextStage,personality:s.personality,idealWeightMin:s.weight[0],idealWeightMax:s.weight[1],health:clamp(p.health+5),happiness:clamp(p.happiness+10)}}
export function advanceTime(pet:Pet,now=Date.now()):{pet:Pet;summary:OfflineSummary}{const raw=(now-pet.lastUpdatedAt)/60000;const anomaly=raw<0;const minutes=Math.max(0,Math.min(raw*TIME_SCALE,60*24*30));const hours=minutes/60;const sleeping=pet.isSleeping;const fullnessLoss=hours*(sleeping?1.4:4.2),happyLoss=hours*(sleeping?.5:1.8),cleanLoss=hours*2.2;const poops=Math.min(5-pet.poopCount,Math.max(0,Math.floor((minutes+(pet.mealsToday+pet.snacksToday)*20)/180)));let health=pet.health;const nextPoops=pet.poopCount+poops;if(pet.cleanliness-cleanLoss<25||nextPoops>=3)health-=hours*1.2;if(pet.fullness-fullnessLoss<15)health-=hours*.7;const sick=(health<42||nextPoops>=4)&&minutes>30;let p:{pet:Pet;summary:OfflineSummary}["pet"]={...pet,lastUpdatedAt:Math.max(pet.lastUpdatedAt,now),ageMinutes:pet.ageMinutes+minutes,fullness:clamp(pet.fullness-fullnessLoss),happiness:clamp(pet.happiness-happyLoss),cleanliness:clamp(pet.cleanliness-cleanLoss),energy:clamp(pet.energy+(sleeping?hours*10:-hours*1.5)),health:clamp(health),weight:+Math.max(.5,pet.weight-(pet.fullness-fullnessLoss<15?hours*.05:0)).toFixed(1),poopCount:nextPoops,isSick:pet.isSick||sick,sicknessType:pet.sicknessType||(sick?(nextPoops>=4?"清潔不足":"過度疲勞"):undefined),careMistakes:pet.careMistakes+(minutes>360&&health<50?1:0)};p=evolveIfReady(p);return{pet:p,summary:{minutes,fullness:+(-fullnessLoss).toFixed(1),happiness:+(-happyLoss).toFixed(1),cleanliness:+(-cleanLoss).toFixed(1),weight:+(p.weight-pet.weight).toFixed(1),poops,clockAnomaly:anomaly}}}
export function buy(coins:number,price:number){if(price<0||coins<price)return{ok:false,coins};return{ok:true,coins:coins-price}}
export function gameReward(score:number){return clamp(5+Math.floor(score/4),5,30)}
export function giveGift(rel:Relationship,gift:Gift,npc:Npc):Relationship{const liked=npc.likes.includes(gift.id),disliked=npc.dislikes.includes(gift.id);return{...rel,affection:clamp(rel.affection+(liked?gift.affectionValue:disliked?2:Math.max(3,Math.floor(gift.affectionValue/2)))),gifts:[...rel.gifts,gift.id]}}
export function canMarry(p:Pet,r:Relationship,hasRing:boolean){return p.stage==="adult"&&p.health>60&&p.happiness>60&&r.affection>=95&&hasRing&&!p.spouseNpcId}
export function marry(p:Pet,r:Relationship,hasRing:boolean,now=Date.now()){return canMarry(p,r,hasRing)?{...p,spouseNpcId:r.npcId,marriedAt:now}:p}
export function memorialize(save:SaveFile,now=Date.now()):SaveFile{if(save.pet.isAlive)return save;const exists=save.game.history.some(h=>h.bornAt===save.pet.birthAt);if(exists)return save;return{...save,game:{...save.game,history:[...save.game.history,{name:save.pet.name,speciesId:save.pet.speciesId,bornAt:save.pet.birthAt,passedAt:now,spouseNpcId:save.pet.spouseNpcId,careGrade:careScore(save.pet)>70?"星光":careScore(save.pet)>45?"溫暖":"相伴"}]}}}
