import {npcs} from "./data";
import {LIFE_MINUTES,STAGE_DURATION_MINUTES,hkDate,stageToNpc} from "./engine";
import type {Pet,Relationship,SaveFile,Stage} from "./types";

type LegacySave={schemaVersion?:number;exportedAt?:number;pet:Partial<Pet>&Pick<Pet,"id"|"stage"|"birthAt"|"lastUpdatedAt"|"speciesId">;game:SaveFile["game"];inventory?:SaveFile["inventory"];relationships?:Relationship[];album?:string[];achievements?:string[];settings?:Record<string,unknown>};
const priorMinutes:Record<Stage,number>={egg:0,baby:1,child:181,teen:901,adult:3061};
export function migrateSaveV1(input:unknown,now=Date.now()):SaveFile{
 const old=input as LegacySave;if(!old?.pet||!old?.game)throw new Error("存檔內容不完整");
 const p=old.pet,stage=p.stage??"egg",stageStartedAt=p.stageStartedAt??p.birthAt+priorMinutes[stage]*60000,nextEvolutionAt=stage==="adult"?undefined:stageStartedAt+STAGE_DURATION_MINUTES[stage]*60000,affection=p.affection??30;
 const pet:Pet={...p,id:p.id,stage,speciesId:p.speciesId,birthAt:p.birthAt,lastUpdatedAt:p.lastUpdatedAt,stageStartedAt,nextEvolutionAt,ageMinutes:p.ageMinutes??Math.max(0,(now-p.birthAt)/60000),lifeExpectancyMinutes:p.lifeExpectancyMinutes??LIFE_MINUTES.base,lifeStage:p.lifeStage??"young",lifetimeCareScore:p.lifetimeCareScore??70,name:p.name??"波波",personality:p.personality??"平靜",health:p.health??90,fullness:p.fullness??75,happiness:p.happiness??80,cleanliness:p.cleanliness??90,energy:p.energy??85,affection,weight:p.weight??2.5,idealWeightMin:p.idealWeightMin??2,idealWeightMax:p.idealWeightMax??3,poopCount:p.poopCount??0,isSick:p.isSick??false,isSleeping:p.isSleeping??false,isAlive:p.isAlive??true,careMistakes:p.careMistakes??0,mealsToday:p.mealsToday??0,snacksToday:p.snacksToday??0,gamesPlayedToday:p.gamesPlayedToday??0,giftsReceived:p.giftsReceived??0,behaviorTags:p.behaviorTags??{active:0,sweetTooth:0,healthy:1,clean:1,affectionate:1,calm:1,neglected:0},dailyPetInteraction:p.dailyPetInteraction??{date:hkDate(now),pettingCount:0,feedingAffectionEarned:0,cleaningAffectionEarned:0,gameAffectionEarned:0},affectionHistory:p.affectionHistory??[{at:now,value:affection,reason:"Schema v2 升級保留"}],affectionLastReason:p.affectionLastReason??"Schema v2 升級保留"};
 const album=old.album??[pet.speciesId],rels:Relationship[]=old.relationships??npcs.map(n=>({npcId:n.id,affection:0,gifts:[]}));
 return{schemaVersion:2,exportedAt:now,pet,game:old.game,inventory:old.inventory??[],relationships:rels.map(r=>({...r,lastTalkDate:r.lastTalkDate??(r.lastTalkAt?hkDate(r.lastTalkAt):undefined)})),album,albumEntries:album.map(id=>({speciesId:id,unlockedAt:now,raisedCount:1})),achievements:old.achievements??[],settings:{theme:"rose",volume:.18,readable:false,highContrast:false,...old.settings},npcProgress:Object.fromEntries(npcs.map(n=>[n.id,{stage:stageToNpc(stage),unlockedLooks:[stageToNpc(stage)],coPlayRewardsToday:0}])),unlockedDecor:[],equippedDecor:[],plantState:{owned:false,placed:false,growth:0},legacyTraits:{unlocked:[]},evolutionHistory:[],itemDefinitionsVersion:2};
}
export function isSaveV2(value:unknown):value is SaveFile{return Boolean(value&&typeof value==="object"&&(value as {schemaVersion?:number}).schemaVersion===2)}
